### ISSUE TITLE
"caddyplug list" has a runtime error

### ISSUE THREAD

**Issue by fanybook** [abiosoft/caddyplug#6]
```
/go/bin # caddyplug list
http:
 ✓ git
   authz
   awses
   awslambda
   cache
   cgi
   cors
   datadog
   expires
   filemanager
   filter
   forwardproxy
   geoip
   gopkg
   grpc
   hugo
   ipfilter
   jekyll
   jsonp
   jwt
   locale
   login
   mailout
   minify
   multipass
   nobots
   prometheus
   proxyprotocol
   ratelimit
   realip
   reauth
   restic
   supervisor
   upload
   webdav
dns:
   auroradns
   azure
   cloudflare
   cloudxns
   digitalocean
   dnsimple
   dnsmadeeasy
   dnspod
   duckdns
   dyn
   exoscale
   fastdns
   gandi
   gandiv5
   generic
   glesys
   godaddy
   googlecloud
   lightsail
   linode
   namecheap
   namedotcom
   ns1
   otc
   ovh
   pdns
   rackspace
   rfc2136
   route53
   vultr
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x462fe6]

goroutine 1 [running]:
sync.(*Once).Do(0x0, 0xc4200d7ab0)
        /usr/local/go/src/sync/once.go:36 +0x26
main.pluginPath(0x519ac4, 0x6, 0xc420211d10, 0x0)
        /go/src/github.com/abiosoft/caddyplug/caddyplug/main.go:126 +0x104
main.Plugin.PluginFile(0x519606, 0x3, 0x5203c1, 0x29, 0x519ac4, 0x6, 0x506940, 0x509701)
        /go/src/github.com/abiosoft/caddyplug/caddyplug/plugin.go:49 +0x3f
main.Plugin.Installed(0x519606, 0x3, 0x5203c1, 0x29, 0x519ac4, 0x6, 0xc0)
        /go/src/github.com/abiosoft/caddyplug/caddyplug/plugin.go:42 +0x41
main.listPlugins.func1(0x1, 0x0, 0x5c2da0)
        /go/src/github.com/abiosoft/caddyplug/caddyplug/command.go:93 +0x68
sort.insertionSort_func(0xc4200d7df0, 0xc420211d40, 0x0, 0x4)
        /usr/local/go/src/sort/zfuncversion.go:12 +0x83
sort.quickSort_func(0xc4200d7df0, 0xc420211d40, 0x0, 0x4, 0x6)
        /usr/local/go/src/sort/zfuncversion.go:158 +0x1f1
sort.Slice(0x4e79c0, 0xc4201ac7c0, 0xc4200d7df0)
        /usr/local/go/src/sort/slice.go:21 +0xe3
main.listPlugins(0x0, 0x0, 0x0)
        /go/src/github.com/abiosoft/caddyplug/caddyplug/command.go:92 +0x305
main.main()
        /go/src/github.com/abiosoft/caddyplug/caddyplug/main.go:69 +0x23e
/go/bin #
```

**Comment by linquize** [comment]
caddyplug/main.go

```go
func pluginPath(pluginType string) string {
        p := filepath.Join(internal.PluginsDir(), pluginType)
        d := once.pluginPath[pluginType]
        if d != nil {
               d.Do(func() {
                       os.MkdirAll(p, 0755)
               })
        }
        return p
}
```
